# Memory wide.
MEMORY_PHYSICAL_PAGES_COUNT = 15
MIN_VIRTUAL_PAGES = 5
MAX_VIRTUAL_PAGES = 20

# Process wide.
PROCESS_STARTING_PID = 3
PROCESS_SPAWN_PROB = 0.1
PROCESS_WORKING_SET_PAGE_ACCESS_PROB = 0.9
PROCESS_ACCESS_MODIFY_PAGE_PROB = 0.3

# Process working time wide.
PROCESS_QUANT = 5
PROCESS_AVG_WORKING_TIME = 40
PROCESS_WORKING_TIME_DEVIATION = 4

# Pages working set wide.
WORKING_SET_PAGES_INITIAL_COUNT = 3

# System wide.
PAGE_DAEMON_CHECKS_PERIOD = 20
PAGE_DAEMON_PAGES_TO_CHECK = 10
PAGE_DAEMON_PID = 2
INITIAL_PROCESSES = 6
SIMULATION_TICKS = 100
